#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh
FORMAT="html"

while [[ $# > 1 ]]
do
key="$1"
shift

case $key in
    -f|--format)
        case $1 in
            cobertura-xml)
                FORMAT="$1"
                shift
             ;;
        esac
        shift
        ;;
esac
done

remove_old_report()
{
    pushd ${BUILT_PRODUCTS_DIR}
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd ${BUILT_PRODUCTS_DIR}
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    LCOV --remove ${LCOV_INFO} "Developer/SDKs/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_html_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

generate_cobertura_xml_report()
{
    TMP_COVERAGE_FILE="/tmp/coverage.xml"
    python "${XCODECOVERAGE_PATH}/lcov_cobertura.py" ${LCOV_INFO} -b ../ -o "$TMP_COVERAGE_FILE"
    cat "$TMP_COVERAGE_FILE"
    rm "$TMP_COVERAGE_FILE"
}

generate_report()
{
    case "$FORMAT" in
    (cobertura-xml)
        generate_cobertura_xml_report
        ;;
    (html|*)
        generate_html_report
        ;;
esac

}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
